"""empty message

Revision ID: 17854785c3b9
Revises: d04d6774c76c
Create Date: 2021-12-29 17:36:20.639887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17854785c3b9'
down_revision = 'd04d6774c76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('team_name', sa.String(), nullable=False))
    op.drop_column('participants', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('participants', 'team_name')
    # ### end Alembic commands ###
